### ISSUE TITLE
Cannot use mode = "satterthwaite" because *lmerTest* package is not installed

### ISSUE THREAD

**Issue by sfirke** [adamMaier/tntpmetrics#1]
I'm getting this error message:
> Cannot use mode = "satterthwaite" because *lmerTest* package is not installed

Should the package require or suggest this package, or is the omission intentional?

**Comment by adamMaier** [comment]
Thanks for flagging, Sam.  That error message is actually being thrown by the `emmeans` package, which I use to process and display results from the linear models working behind the scenes. It used to work with just the `lme4::lmer` function but appears it might now require the models be run by `lmerTest::lmer` to use the degrees of freedom approach I have it set to. I changed the underlying code to use `lmerTest::lmer` instead -- the underlying model is the same, but `lmerTest` also provides more statistical significance testing -- and have it imported in the package. Let me know if that works for you, now.

**Comment by sfirke** [comment]
This makes sense then, `lmerTest` is only Suggested by `emmeans`, not required.  And importing it to `tntpmetrics` makes sense.  I haven't tried it out now, since I have `lmerTest` installed now, but based on your described change I'll close this.  Thanks for looking into it!
